branches:
  only:
  - master

language: node_js
node_js:
  - "8"

script:
  - node build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_API_TOKEN 
  keep_history: true
  local_dir: docs/
  on:
    branch: master